name: "Validate Gradle Wrapper"
on: [push, pull_request]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      # allstar complains if we don't use tags here (https://github.com/ossf/scorecard/issues/2477)
      - uses: gradle/wrapper-validation-action@v1
