name: "Validate Gradle Wrapper"
on: [push, pull_request]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      # allstar complains if we don't use tags here (https://github.com/ossf/scorecard/issues/2477)
      - uses: gradle/wrapper-validation-action@v3
